version: "3.5"

services:
  postgresql:
    container_name: "postgresql"
    hostname: "postgresql"
    image: "postgres:15.1"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_volume:
    name: postgres_db
